### ISSUE TITLE
Create a weather app template

### ISSUE THREAD

**Issue by simranquirky** [simranquirky/Frontend_templates#16]
Weather app template only frontend

**Comment by SrishtiArya07** [comment]
@simranquirky I want to work on this issue. Please assign it to me.

**Comment by simranquirky** [comment]
Ok upload your files inside a folder 'weather'

**Comment by mifrasgaffoor** [comment]
I want to work on this issue.  could you please assign it to me?

**Comment by simranquirky** [comment]
Yes just create a separate folder within the 'weather' folder

**Comment by aniket1104** [comment]
i want to work on this issue....please assign me this task

**Comment by simranquirky** [comment]
Ok create a separate folder for your work @aniket1104

**Comment by aniket1104** [comment]
okay..i ll create a seperate folder.
