### ISSUE TITLE
Create a news portal template

### ISSUE THREAD

**Issue by simranquirky** [simranquirky/Frontend_templates#17]
News portal template only frontend

**Comment by Chetana16032002** [comment]
I will work on this issue please assign this to me 🤗

**Comment by Sundar-07** [comment]
Hi, May I know what is the problem here? @simranquirky 

remote: Permission to simranquirky/Frontend_templates.git denied to Sundar-07.
fatal: unable to access 'https://github.com/simranquirky/Frontend_templates.git/': The requested URL returned error: 403

**Comment by simranquirky** [comment]
> Hi, May I know what is the problem here? @simranquirky
> 
> remote: Permission to simranquirky/Frontend_templates.git denied to Sundar-07. fatal: unable to access 'https://github.com/simranquirky/Frontend_templates.git/': The requested URL returned error: 403

Remove the / in the end
Try https://github.com/simranquirky/Frontend_templates.git
