### ISSUE TITLE
create a login page using neumorphism

### ISSUE THREAD

**Issue by simranquirky** [simranquirky/Frontend_templates#3]
create a login page using neumorphism which takes email id and password as input

**Comment by arunim-iiitlCS** [comment]
I want to contribute to this please assign me under hacktoberfest tag.

**Comment by dhruvgarg02** [comment]
I would like to work on this. Kindly Assign me the issue.

**Comment by arunim-iiitlCS** [comment]
Please see PR #12 

Thanks and Regards

**Comment by simranquirky** [comment]
You pr is merged successfully. Thanks for your contribution
