### ISSUE TITLE
create a food-blog site

### ISSUE THREAD

**Issue by simranquirky** [simranquirky/Frontend_templates#4]
create a single page  food-blog site

**Comment by sarcasvik** [comment]
some time back i made a restaurant webpage can I make some changes in that and make a PR instead of food-blog site?

**Comment by simranquirky** [comment]
yes sure just create a new folder restaurant webpage and upload your files there

**Comment by Chetana16032002** [comment]
I will work on this issue please assign this to me 🤗

**Comment by 15Shreya** [comment]
I want to work on this. Please assign it to me.

**Comment by 15Shreya** [comment]
Thank you.

**Comment by Ashu-1309** [comment]
I want to work on the issue kindly assign me

**Comment by simranquirky** [comment]
> I want to work on the issue kindly assign me

Create a separate folder and start working on it.
