### ISSUE TITLE
create a shopping site

### ISSUE THREAD

**Issue by simranquirky** [simranquirky/Frontend_templates#5]
can be a clone or normal shopping site

**Comment by mifrasgaffoor** [comment]
I want to work on this issue.
and what are technologies have to use?

**Comment by simranquirky** [comment]
Any frontend tools html css js bootstrap react etc

**Comment by mifrasgaffoor** [comment]
ok, I will do using pure HTML CSS  is it ok?

could you assign me

**Comment by simranquirky** [comment]
Yes sure just make sure to create a separate folder within the shopping site folder

**Comment by Chetana16032002** [comment]
I can do a shopping website too I can name the folder as shopping site_2

**Comment by simranquirky** [comment]
Sure

**Comment by Bhawna147** [comment]
hey @simranquirky I'm good at designing websites using HTML & CSS  , will you please assign this issue to me

**Comment by simranquirky** [comment]
> hey @simranquirky I'm good at designing websites using HTML & CSS , will you please assign this issue to me

Create a separate folder and start working
