### ISSUE TITLE
registration form for students

### ISSUE THREAD

**Issue by simranquirky** [simranquirky/Frontend_templates#8]

**Comment by Ashu-1309** [comment]
I want to work on this issue .

**Comment by Ashu-1309** [comment]
@simranquirky  Can you please explain what I have to do in this ??

**Comment by simranquirky** [comment]
you have to create an html file where we take input such as student name, roll, class, sections, subjects enrolled,schoolname etc and a submit button. ni backend work involved , just HTML CSS and js.

**Comment by Ashu-1309** [comment]
Okay , Basically you are saying that the login information have to save in DBMS .right ????

**Comment by simranquirky** [comment]
"no backend work"

**Comment by Ashu-1309** [comment]
Okay . So kindly assign me this work . I want to work on it .

**Comment by simranquirky** [comment]
sure

**Comment by Ashu-1309** [comment]
Thank you @simranquirky for assigning me this work .

**Comment by mifrasgaffoor** [comment]
hey, @simranquirky  could I please upload the Registration form with javascript validation for students.

**Comment by simranquirky** [comment]
Yes just create a separate folder for that @mifrasgaffoor

**Comment by Saurabhsahab** [comment]
@simranquirky I want to work on this please assign it to me

**Comment by simranquirky** [comment]
Ok create. A separate folder for your work.

**Comment by YashGupta29** [comment]
@simranquirky I would like to contribute to this. Please can you assign it to me?

**Comment by simranquirky** [comment]
Yes. Make sure to create a separate folder.

**Comment by 15Shreya** [comment]
I would like to work on this. Please assign it to me.
